name: Lightning Action
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  lightning-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: checkout pull request branch
    uses: actions/checkout@v2
    with:
        python-version: ${{ matrix.python-version }}
    - name: install requirement
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt